#!/usr/bin/env python3

# Description: Checks status of all Git repos found in specific directory, or
# all Git repos found one sub-level down. State of repo is indicated through
# colors green (clean), yellow (unpushed) and red (dirty). Characters * (dirty)
# and + (unpushed) are printed next to branch names for colorless operation.
#
# Example:
#
#     /Users/GLEG/Projects:
#     Ansiblebot      master
#     Dotfiles        master*
#     Project-Assets  master
#     ...
#
# Dependencies: pytt.py + termcolors.py
#     https://github.com/ggustafsson/Pyttipanna/blob/master/src/lib/pytt.py
#     https://github.com/ggustafsson/Pyttipanna/blob/master/src/lib/termcolors.py
#
# Usage: gitst
#
# Author: Göran Gustafsson <gustafsson.g@gmail.com>
# License: BSD 3-Clause

import argparse
import os
import subprocess
import sys

from collections import namedtuple

from lib.pytt import git_find
from lib.termcolors import Attr, Fg


def setup_args() -> argparse.Namespace:
    """Configure argument parsing."""

    parser = argparse.ArgumentParser(
        description="Check status of Git repos in directory."
    )
    parser.add_argument(
        "-p", "--path",
        default=os.path.expanduser("~/Projects"),
        help="directory to search (default: ~/Projects)"
    )
    parser.add_argument(
        "-s", "--sub-level",
        action="store_true",
        help="search one sub-level down (default: off)"
    )
    return parser.parse_args()


def git_status(repo_dir: os.DirEntry, sub_level: bool = False) -> tuple:
    """Check Git repo status.

    Retrieve information about current branch and state (dirty/unpushed).

    Arguments:
        repo_dir: os.DirEntry containing Git repo directory.
        sub_level: bool that sets if name should contain parent directory.

    Returns:
        namedtuple containing Git repo status.
        repo(name='x', branch='y', dirty=False, unpushed=False)
    """

    if sub_level:
        path = str(repo_dir.path).split(os.sep)
        name = f"{path[-2]}{os.sep}{path[-1]}"
    else:
        name = repo_dir.name

    proc = subprocess.run(
        ["git", "-C", repo_dir.path, "branch", "--show-current"],
        capture_output=True,
        check=False
    )
    branch = proc.stdout.decode().strip()

    proc = subprocess.run(
        ["git", "-C", repo_dir.path, "status", "--porcelain"],
        capture_output=True,
        check=False
    )
    dirty = bool(len(proc.stdout) > 0)

    if not dirty:
        proc = subprocess.run(
            ["git", "-C", repo_dir.path, "log", "-n", "1", "@{upstream}.."],
            capture_output=True,
            check=False
        )
        unpushed = bool(len(proc.stdout) > 0)
    else:
        unpushed = False

    repo = namedtuple("repo", "name branch dirty unpushed")
    return repo(name=name, branch=branch, dirty=dirty, unpushed=unpushed)


def git_table(repos: list):
    """Print summary table of Git repos.

    State of repo is indicated through colors green (clean), yellow (unpushed)
    and red (dirty). Characters * (dirty) and + (unpushed) are printed next to
    branch names for colorless operation.

    Arguments:
        repos: list containing dict's with Git repo states.
    """

    column = len(max((repo.name for repo in repos), key=len)) + 2

    for repo in repos:
        print(f"{repo.name:<{column}}", end="")
        if repo.dirty:
            print(f"{Fg.BrightRed}{repo.branch}*{Attr.Reset}")
        elif repo.unpushed:
            print(f"{Fg.BrightYellow}{repo.branch}+{Attr.Reset}")
        else:
            print(f"{Fg.BrightGreen}{repo.branch}{Attr.Reset}")


def main():
    args = setup_args()

    if not os.path.isdir(args.path):
        print(f"Directory '{args.path}' not found! Exiting...")
        sys.exit(1)

    print(f"{Fg.BrightCyan}{args.path}:{Attr.Reset}")

    repos = git_find(args.path, args.sub_level)
    if len(repos) > 0:
        states = [git_status(repo, args.sub_level) for repo in repos]
        git_table(states)
    else:
        print("No Git repos found...")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print()
