#!/usr/bin/env python3

# Description: Reformats text following English title capitalization rules.
# Takes input text through arguments or STDIN and prints titelized version.
#
# Lowercase:
#
#     a, an, and, as, at, but, by, en, etc, for, from,
#     if, in, of, on, or, the, to, via, von, vs, with
#
# Example:
#
#     $ title "tears for fears @ rule the world: the greatest hits"
#     Tears for Fears @ Rule the World: The Greatest Hits
#
# Dependencies: title
#     https://github.com/ggustafsson/Pyttipanna/blob/master/src/lib/title.py
#
# Usage: title <text>
#        title < <file>
#        cat <file> | title
#
# Author: Göran Gustafsson <gustafsson.g@gmail.com>
# License: BSD 3-Clause

import sys

from lib.title import titleize


def main():
    if len(sys.argv) > 1:
        # When executed as: title <text>
        text = str.join(" ", sys.argv[1:])
        print(titleize(text))
    else:
        # When executed as: title < <file>
        for line in sys.stdin:
            print(titleize(line))


if __name__ == "__main__":
    try:
        main()
    # Do not print traceback after ^C exit.
    except KeyboardInterrupt:
        print()
